"""Integration tests for the HTTP API.

These drive the real application through a real HTTP client against a real
SQLite database. Nothing is mocked: if a route is not wired up, or a dependency
does not resolve, or the response schema does not match what the handler returns,
these fail.

The tenant-isolation tests are the ones worth reading. A multi-tenant security
product that leaks across tenants is worse than one that does not work at all,
so isolation is tested from several angles rather than assumed from the presence
of a ``WHERE`` clause.
"""

from __future__ import annotations

import uuid

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import select

from veyl_api.api.main import create_app
from veyl_api.api.routes import members as members_route
from veyl_api.db.base import utcnow
from veyl_api.enums import OrganizationRole
from veyl_api.models import Organization, OrganizationMember, User
from veyl_api.security.auth import hash_password

STRONG_PASSWORD = "Correct-Horse-Battery-9!"
#: The TOTP secret the test administrator enrols. A fixed value is used so the
#: test can compute the expected code rather than reaching into the database;
#: the code is still generated by the real algorithm against the real time.
ADMIN_TOTP_SECRET = "JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP"


@pytest.fixture()
def client(session):
    """A TestClient bound to the per-test database.

    The app is rebuilt per test so nothing carries over, and the *dependency
    object* the routes actually reference is overridden. Overriding
    ``session_module.get_session`` would not work: ``deps`` imported that
    function by name at import time, so the routes hold the original object.
    """
    from veyl_api.api import deps

    app = create_app()

    def _override_session():
        yield session

    app.dependency_overrides[deps.get_session] = _override_session
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()


@pytest.fixture()
def admin(session):
    """An organization with one administrator, ready to log in.

    The administrator has a TOTP factor enrolled, because §27 refuses to
    authenticate an administrative account without one. Tests that want to
    exercise the refusal itself build their own factorless admin — see
    ``test_an_admin_without_a_factor_cannot_sign_in``.
    """
    from veyl_api.api.routes.auth import _hash_totp_secret

    org = Organization(
        name="AcmePay", slug=f"acmepay-{uuid.uuid4().hex[:8]}", primary_domain="acmepay.example"
    )
    session.add(org)
    session.flush()

    user = User(
        email=f"admin-{uuid.uuid4().hex[:6]}@acmepay.example",
        full_name="Ada Admin",
        password_hash=hash_password(STRONG_PASSWORD),
        is_active=True,
        mfa_enabled=True,
        mfa_secret_hash=_hash_totp_secret(ADMIN_TOTP_SECRET),
        mfa_enrolled_at=utcnow(),
    )
    session.add(user)
    session.flush()

    session.add(
        OrganizationMember(
            organization_id=org.id,
            user_id=user.id,
            role=OrganizationRole.ADMIN,
            is_active=True,
        )
    )
    session.commit()
    return {"org": org, "user": user, "password": STRONG_PASSWORD, "totp": ADMIN_TOTP_SECRET}


def totp_for(secret: str = ADMIN_TOTP_SECRET) -> str:
    """The code an authenticator would show right now."""
    from veyl_api.security.mfa import totp_now

    return totp_now(secret)


def login(client, admin, *, password: str | None = None, code: str | None = None):
    """Sign in as the test administrator, supplying the current TOTP code.

    Kept as a helper so the many tests that just need a session do not each have
    to know about the second factor. Tests that care about the factor call
    ``client.post`` directly.
    """
    payload = {
        "email": admin["user"].email,
        "password": admin["password"] if password is None else password,
    }
    if code is not False:
        payload["totp_code"] = totp_for(admin.get("totp", ADMIN_TOTP_SECRET)) if code is None else code
    return client.post("/api/auth/login", json=payload)


def login_as(client, email: str, secret: str, *, password: str = STRONG_PASSWORD, **extra):
    """Sign in as any account whose TOTP secret the test knows."""
    return client.post(
        "/api/auth/login",
        json={
            "email": email,
            "password": password,
            "totp_code": totp_for(secret),
            **extra,
        },
    )


@pytest.fixture()
def auth_headers(client, admin):
    """Bearer headers for the administrator."""
    response = login(client, admin)
    assert response.status_code == 200, response.text
    return {"Authorization": f"Bearer {response.json()['access_token']}"}


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------


def test_health_is_public(client):
    response = client.get("/api/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_readiness_reports_the_database(client):
    body = client.get("/api/health/ready").json()
    assert body["checks"]["database"] is True
    assert body["status"] == "ok"


def test_security_headers_are_present(client):
    response = client.get("/api/health")
    assert response.headers["X-Content-Type-Options"] == "nosniff"
    assert response.headers["X-Frame-Options"] == "DENY"
    assert response.headers["Cache-Control"] == "no-store"
    assert response.headers["X-Request-ID"]


def test_request_id_is_echoed_when_supplied(client):
    response = client.get("/api/health", headers={"X-Request-ID": "abc123"})
    assert response.headers["X-Request-ID"] == "abc123"


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------


def test_login_returns_a_token_pair(client, admin):
    response = login(client, admin)
    assert response.status_code == 200
    body = response.json()
    assert body["token_type"] == "bearer"
    assert body["access_token"] and body["refresh_token"]
    assert body["expires_in"] > 0


def test_login_with_a_wrong_password_is_refused(client, admin):
    response = login(client, admin, password="Wrong-Password-1!")
    assert response.status_code == 401
    assert "invalid email or password" in response.json()["detail"]


def test_login_for_an_unknown_user_looks_identical_to_a_wrong_password(client):
    """The response must not reveal whether an address is registered."""
    unknown = client.post(
        "/api/auth/login",
        json={"email": "nobody@nowhere.example", "password": "Whatever-1234!"},
    )
    assert unknown.status_code == 401
    assert unknown.json()["detail"] == "invalid email or password"


def test_login_failure_is_audited(client, admin, session):
    from veyl_api.models import AuditLog

    login(client, admin, password="Wrong-Password-1!")
    session.expire_all()
    entries = list(
        session.execute(
            select(AuditLog).where(AuditLog.action == "LOGIN_FAILED")
        ).scalars()
    )
    assert len(entries) == 1
    assert entries[0].result == "FAILURE"


def test_login_success_is_audited(client, admin, session):
    from veyl_api.models import AuditLog

    login(client, admin)
    session.expire_all()
    entries = list(
        session.execute(select(AuditLog).where(AuditLog.action == "LOGIN")).scalars()
    )
    assert len(entries) == 1
    assert entries[0].actor_email == admin["user"].email


def test_me_describes_the_caller_and_their_permissions(client, auth_headers):
    body = client.get("/api/auth/me", headers=auth_headers).json()
    assert body["role"] == "ADMIN"
    assert body["active_organization_id"]
    assert len(body["organizations"]) == 1
    # Capabilities are computed server-side from the enforced table.
    assert "scan:create" in body["capabilities"]
    assert "scope:write" in body["capabilities"]


def test_refresh_issues_a_new_pair(client, admin):
    tokens = login(client, admin).json()
    response = client.post(
        "/api/auth/refresh", json={"refresh_token": tokens["refresh_token"]}
    )
    assert response.status_code == 200
    assert response.json()["access_token"]


def test_an_access_token_is_not_accepted_as_a_refresh_token(client, admin):
    tokens = login(client, admin).json()
    response = client.post(
        "/api/auth/refresh", json={"refresh_token": tokens["access_token"]}
    )
    assert response.status_code == 401
    assert "expected a refresh token" in response.json()["detail"]


def test_a_garbage_token_is_refused(client):
    response = client.get("/api/assets", headers={"Authorization": "Bearer not.a.jwt"})
    assert response.status_code == 401


def test_deactivating_a_user_invalidates_their_token(client, admin, session, auth_headers):
    """Authorization is re-read per request, so revocation is immediate."""
    assert client.get("/api/auth/me", headers=auth_headers).status_code == 200

    user = session.get(User, admin["user"].id)
    user.is_active = False
    session.commit()

    assert client.get("/api/auth/me", headers=auth_headers).status_code == 401


# ---------------------------------------------------------------------------
# Second factors (§27)
# ---------------------------------------------------------------------------


def test_a_correct_password_without_a_code_is_refused_and_named(client, admin):
    """The password alone must not produce a session when a factor is enrolled."""
    response = login(client, admin, code=False)
    assert response.status_code == 401
    detail = response.json()["detail"]
    assert detail["mfa_required"] is True
    assert "totp" in detail["methods"]
    assert "access_token" not in response.json()


def test_a_wrong_totp_code_is_refused(client, admin):
    response = login(client, admin, code="000000")
    assert response.status_code == 401
    assert "second-factor code" in response.json()["detail"]


def test_a_valid_totp_code_completes_the_login(client, admin):
    response = login(client, admin)
    assert response.status_code == 200
    assert response.json()["access_token"]


def test_a_totp_code_is_rejected_once_its_window_has_passed(client, admin):
    """A code from an hour ago must not be accepted."""
    from datetime import timedelta

    from veyl_api.db.base import utcnow
    from veyl_api.security.mfa import totp_now

    stale = totp_now(admin["totp"], at=utcnow() - timedelta(hours=1))
    response = login(client, admin, code=stale)
    assert response.status_code == 401


def test_the_totp_factor_uses_the_real_algorithm(client, admin):
    """Prove the accepted code is the one RFC 6238 produces, not a stored value."""
    from veyl_api.security.mfa import verify_totp

    code = totp_for(admin["totp"])
    assert verify_totp(admin["totp"], code)
    assert not verify_totp(admin["totp"], "123456")
    assert login(client, admin, code=code).status_code == 200


def test_a_successful_factor_is_audited(client, admin, session):
    from veyl_api.models import AuditLog

    login(client, admin)
    session.expire_all()
    actions = {e.action for e in session.execute(select(AuditLog)).scalars()}
    assert "MFA_VERIFIED" in {str(a) for a in actions}


def test_an_admin_without_a_factor_cannot_sign_in(client, session):
    """The §27 policy, stated as a test.

    An administrative role is not usable without a second factor. This is
    enforced at login rather than only at enrolment, because enforcement at
    enrolment alone would leave any account that already held the role usable.
    """
    org = Organization(
        name="NoFactor", slug=f"nofactor-{uuid.uuid4().hex[:8]}", primary_domain="nf.example"
    )
    session.add(org)
    session.flush()

    user = User(
        email=f"bare-admin-{uuid.uuid4().hex[:6]}@nf.example",
        full_name="Bare Admin",
        password_hash=hash_password(STRONG_PASSWORD),
        is_active=True,
    )
    session.add(user)
    session.flush()
    session.add(
        OrganizationMember(
            organization_id=org.id,
            user_id=user.id,
            role=OrganizationRole.ADMIN,
            is_active=True,
        )
    )
    session.commit()

    response = client.post(
        "/api/auth/login",
        json={"email": user.email, "password": STRONG_PASSWORD},
    )
    assert response.status_code == 403
    assert "second factor" in response.json()["detail"]


def test_repeated_failures_lock_the_account(client, admin):
    """Guessing must stop being possible after a bounded number of attempts."""
    from veyl_api.security.mfa import LOCKOUT_THRESHOLD

    for _ in range(LOCKOUT_THRESHOLD):
        response = login(client, admin, password="Wrong-Password-1!")
        assert response.status_code in (401, 423)

    locked = login(client, admin, password="Wrong-Password-1!")
    assert locked.status_code == 423
    assert "locked" in locked.json()["detail"]


def test_a_locked_account_refuses_even_the_correct_password(client, admin, session):
    from veyl_api.security.mfa import LOCKOUT_THRESHOLD

    for _ in range(LOCKOUT_THRESHOLD):
        login(client, admin, password="Wrong-Password-1!")

    session.expire_all()
    response = login(client, admin)
    assert response.status_code == 423


def test_a_lockout_is_audited(client, admin, session):
    from veyl_api.models import AuditLog
    from veyl_api.security.mfa import LOCKOUT_THRESHOLD

    for _ in range(LOCKOUT_THRESHOLD):
        login(client, admin, password="Wrong-Password-1!")

    session.expire_all()
    actions = {str(e.action) for e in session.execute(select(AuditLog)).scalars()}
    assert "ACCOUNT_LOCKED" in actions


def test_a_successful_login_clears_the_failure_counter(client, admin, session):
    login(client, admin, password="Wrong-Password-1!")
    login(client, admin, password="Wrong-Password-1!")

    session.expire_all()
    user = session.get(User, admin["user"].id)
    assert user.failed_login_count == 2

    assert login(client, admin).status_code == 200

    session.expire_all()
    user = session.get(User, admin["user"].id)
    assert user.failed_login_count == 0
    assert user.locked_until is None


def test_security_posture_reports_the_policy_gap(client, auth_headers):
    body = client.get("/api/auth/security", headers=auth_headers).json()
    assert body["has_totp"] is True
    assert body["has_hardware_key"] is False
    assert body["privileged_roles"] == ["ADMIN"]
    assert body["meets_privileged_policy"] is True
    assert body["session_ttl_minutes"] > 0
    # Concrete advice, not a score.
    assert any("hardware" in r.lower() for r in body["recommendations"])


def test_security_posture_requires_authentication(client):
    assert client.get("/api/auth/security").status_code == 401


def test_totp_enrolment_returns_a_secret_once_and_does_not_activate_it(client, auth_headers):
    """Enrolment must not switch the factor on before the user proves it works."""
    response = client.post("/api/auth/mfa/totp/enrol", headers=auth_headers)
    assert response.status_code == 200
    body = response.json()
    assert body["secret"]
    assert body["provisioning_uri"].startswith("otpauth://totp/")
    assert len(body["recovery_codes"]) == 10

    # Not yet active: the account has a pending secret but mfa_enabled is false,
    # so the previously working code is no longer the one that verifies.
    posture = client.get("/api/auth/security", headers=auth_headers).json()
    assert posture["has_totp"] is False


def test_enrolment_requires_authentication(client):
    assert client.post("/api/auth/mfa/totp/enrol").status_code == 401


def test_confirming_an_enrolment_with_the_right_code_activates_it(client, auth_headers):
    from veyl_api.security.mfa import totp_now

    enrolled = client.post("/api/auth/mfa/totp/enrol", headers=auth_headers).json()
    code = totp_now(enrolled["secret"])

    response = client.post(
        "/api/auth/mfa/totp/confirm", headers=auth_headers, json={"code": code}
    )
    assert response.status_code == 200
    assert response.json()["mfa_enabled"] is True

    posture = client.get("/api/auth/security", headers=auth_headers).json()
    assert posture["has_totp"] is True


def test_confirming_an_enrolment_with_the_wrong_code_does_not_activate_it(client, auth_headers):
    client.post("/api/auth/mfa/totp/enrol", headers=auth_headers)
    response = client.post(
        "/api/auth/mfa/totp/confirm", headers=auth_headers, json={"code": "000000"}
    )
    assert response.status_code == 400
    posture = client.get("/api/auth/security", headers=auth_headers).json()
    assert posture["has_totp"] is False


def test_confirming_without_an_enrolment_in_progress_is_a_conflict(client, session):
    """A user with no pending secret cannot conjure one."""
    org = Organization(
        name="Conf", slug=f"conf-{uuid.uuid4().hex[:8]}", primary_domain="c.example"
    )
    session.add(org)
    session.flush()
    user = User(
        email=f"analyst-{uuid.uuid4().hex[:6]}@c.example",
        full_name="Ana Analyst",
        password_hash=hash_password(STRONG_PASSWORD),
        is_active=True,
    )
    session.add(user)
    session.flush()
    session.add(
        OrganizationMember(
            organization_id=org.id,
            user_id=user.id,
            role=OrganizationRole.SECURITY_ANALYST,
            is_active=True,
        )
    )
    session.commit()

    tokens = client.post(
        "/api/auth/login", json={"email": user.email, "password": STRONG_PASSWORD}
    ).json()
    headers = {"Authorization": f"Bearer {tokens['access_token']}"}

    response = client.post(
        "/api/auth/mfa/totp/confirm", headers=headers, json={"code": "000000"}
    )
    assert response.status_code == 409


def test_disabling_totp_requires_the_password(client, auth_headers):
    response = client.post(
        "/api/auth/mfa/disable", headers=auth_headers, json={"password": "Wrong-Password-1!"}
    )
    assert response.status_code == 401

    posture = client.get("/api/auth/security", headers=auth_headers).json()
    assert posture["has_totp"] is True


def test_an_admin_cannot_disable_their_only_factor(client, auth_headers):
    """Removing the factor would leave administrative capability unbacked."""
    response = client.post(
        "/api/auth/mfa/disable", headers=auth_headers, json={"password": STRONG_PASSWORD}
    )
    assert response.status_code == 409
    assert "administrative" in response.json()["detail"].lower()


def test_a_non_admin_can_disable_totp_with_their_password(client, session):
    """Only a privileged role is blocked from removing its factor.

    An engineer with a real enrolled factor must be able to turn it off, given
    the password. This test uses the actual encryption path so the login it
    performs is a genuine one.
    """
    from veyl_api.api.routes.auth import _hash_totp_secret
    from veyl_api.security.mfa import totp_now

    secret = "KRSXG5CTMVRXEZLUKRSXG5CTMVRXEZLU"
    org = Organization(name="Eng", slug=f"eng-{uuid.uuid4().hex[:8]}", primary_domain="e.example")
    session.add(org)
    session.flush()
    user = User(
        email=f"eng-{uuid.uuid4().hex[:6]}@e.example",
        full_name="Eve Engineer",
        password_hash=hash_password(STRONG_PASSWORD),
        is_active=True,
        mfa_enabled=True,
        mfa_secret_hash=_hash_totp_secret(secret),
        mfa_enrolled_at=utcnow(),
    )
    session.add(user)
    session.flush()
    session.add(
        OrganizationMember(
            organization_id=org.id,
            user_id=user.id,
            role=OrganizationRole.ENGINEER,
            is_active=True,
        )
    )
    session.commit()

    login_response = client.post(
        "/api/auth/login",
        json={
            "email": user.email,
            "password": STRONG_PASSWORD,
            "totp_code": totp_now(secret),
        },
    )
    assert login_response.status_code == 200, login_response.text
    headers = {"Authorization": f"Bearer {login_response.json()['access_token']}"}

    response = client.post(
        "/api/auth/mfa/disable", headers=headers, json={"password": STRONG_PASSWORD}
    )
    assert response.status_code == 200, response.text
    assert response.json()["mfa_enabled"] is False

    posture = client.get("/api/auth/security", headers=headers).json()
    assert posture["has_totp"] is False


def test_webauthn_registration_options_issue_a_challenge(client, auth_headers):
    response = client.post("/api/auth/webauthn/register/options", headers=auth_headers)
    assert response.status_code == 200
    body = response.json()
    assert body["challenge"]
    assert body["rp_id"]
    assert -7 in body["algorithms"]  # ES256 must be offered
    # The user handle must not be the email; it is what goes onto the hardware.
    assert body["user_id"] != body["user_name"]


def test_a_challenge_is_single_use(client, auth_headers, session):
    """Replaying a challenge must fail — this is the replay defence."""
    from veyl_api.models import AuthChallenge
    from veyl_api.security.mfa import MFAError
    from veyl_api.security.webauthn import consume_challenge

    body = client.post("/api/auth/webauthn/register/options", headers=auth_headers).json()
    consume_challenge(session, challenge=body["challenge"], purpose="registration")
    session.commit()

    with pytest.raises(MFAError, match="already been used"):
        consume_challenge(session, challenge=body["challenge"], purpose="registration")

    assert session.execute(select(AuthChallenge)).scalars().first() is not None


def test_a_challenge_from_another_purpose_is_refused(client, auth_headers, session):
    """A registration challenge must not be usable for authentication."""
    from veyl_api.security.mfa import MFAError
    from veyl_api.security.webauthn import consume_challenge

    body = client.post("/api/auth/webauthn/register/options", headers=auth_headers).json()
    with pytest.raises(MFAError):
        consume_challenge(session, challenge=body["challenge"], purpose="authentication")


def _minimal_attestation_object() -> str:
    """A well-formed CBOR attestation object: ``{"fmt": "none", "authData": <37 zeros>}``.

    Shared by the origin tests so that the check under test is the one that
    fails, rather than an earlier parse error standing in for it.
    """
    import base64

    auth_data = b"\x00" * 37
    cbor = (
        b"\xa2"
        b"\x63fmt"  # text(3) "fmt"
        b"\x64none"  # text(4) "none"
        b"\x68authData"  # text(8) "authData"
        b"\x58\x25" + auth_data  # byte string, 1-byte length, 37 items
    )
    return base64.urlsafe_b64encode(cbor).decode().rstrip("=")


def test_a_webauthn_registration_with_a_forged_payload_is_refused(client, auth_headers):
    """No partial trust: a payload that does not verify is never stored.

    The attestation object is well-formed, so the origin check is what rejects
    it rather than an earlier parse failure. Testing the origin rule requires
    getting past the format rules first.
    """
    import base64
    import json as _json

    options = client.post(
        "/api/auth/webauthn/register/options", headers=auth_headers
    ).json()

    client_data = {
        "type": "webauthn.create",
        "challenge": options["challenge"],
        "origin": "https://attacker.example",  # not an allowed origin
    }
    forged_client_data = base64.urlsafe_b64encode(
        _json.dumps(client_data).encode()
    ).decode().rstrip("=")

    response = client.post(
        "/api/auth/webauthn/register",
        headers=auth_headers,
        json={
            "credential_id": "A" * 32,
            "client_data_json": forged_client_data,
            "attestation_object": _minimal_attestation_object(),
            "label": "Forged",
        },
    )
    assert response.status_code == 400, response.text
    assert "origin" in response.json()["detail"].lower()

    posture = client.get("/api/auth/security", headers=auth_headers).json()
    assert posture["has_hardware_key"] is False


def test_a_webauthn_registration_with_a_malformed_attestation_is_refused(client, auth_headers):
    """A format error is reported as a format error, not silently accepted."""
    response = client.post(
        "/api/auth/webauthn/register",
        headers=auth_headers,
        json={
            "credential_id": "A" * 32,
            "client_data_json": "AAAA",
            "attestation_object": "AAAA",
            "label": "Malformed",
        },
    )
    assert response.status_code == 400
    assert "cbor" in response.json()["detail"].lower()


def test_a_webauthn_registration_from_a_wrong_origin_is_refused(client, auth_headers):
    """The origin rule is the phishing defence; prove it fires on its own."""
    import base64
    import json as _json

    options = client.post(
        "/api/auth/webauthn/register/options", headers=auth_headers
    ).json()
    client_data = {
        "type": "webauthn.create",
        "challenge": options["challenge"],
        "origin": "http://localhost:9999",  # a real port, but not an allowed origin
    }
    encoded = base64.urlsafe_b64encode(_json.dumps(client_data).encode()).decode().rstrip("=")

    response = client.post(
        "/api/auth/webauthn/register",
        headers=auth_headers,
        json={
            "credential_id": "B" * 32,
            "client_data_json": encoded,
            "attestation_object": _minimal_attestation_object(),
            "label": "Wrong origin",
        },
    )
    assert response.status_code == 400
    assert "origin" in response.json()["detail"].lower()


def test_a_registration_with_the_wrong_ceremony_type_is_refused(client, auth_headers):
    """A ``webauthn.get`` ceremony must not be accepted as a registration."""
    import base64
    import json as _json

    options = client.post(
        "/api/auth/webauthn/register/options", headers=auth_headers
    ).json()
    origin = "http://localhost:3000"
    client_data = {
        "type": "webauthn.get",  # wrong ceremony
        "challenge": options["challenge"],
        "origin": origin,
    }
    encoded = base64.urlsafe_b64encode(_json.dumps(client_data).encode()).decode().rstrip("=")

    response = client.post(
        "/api/auth/webauthn/register",
        headers=auth_headers,
        json={
            "credential_id": "C" * 32,
            "client_data_json": encoded,
            "attestation_object": _minimal_attestation_object(),
            "label": "Wrong ceremony",
        },
    )
    assert response.status_code == 400
    assert "webauthn.create" in response.json()["detail"]


def test_an_unknown_credential_cannot_be_asserted(client, auth_headers):
    response = client.post(
        "/api/auth/webauthn/authenticate",
        headers=auth_headers,
        json={
            "credential_id": "N" * 32,
            "client_data_json": "AAAA",
            "authenticator_data": "AAAA",
            "signature": "AAAA",
        },
    )
    assert response.status_code == 404


def test_webauthn_authenticate_requires_authentication(client):
    response = client.post(
        "/api/auth/webauthn/authenticate",
        json={
            "credential_id": "N" * 32,
            "client_data_json": "AAAA",
            "authenticator_data": "AAAA",
            "signature": "AAAA",
        },
    )
    assert response.status_code == 401


# ---------------------------------------------------------------------------
# Authentication is required, and enforced per capability
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "method,path",
    [
        ("get", "/api/assets"),
        ("get", "/api/scope"),
        ("get", "/api/scans"),
        ("get", "/api/findings"),
        ("get", "/api/changes"),
        ("get", "/api/graph"),
        ("get", "/api/attack-paths"),
        ("get", "/api/reports"),
        ("get", "/api/audit"),
        ("get", "/api/members"),
        ("get", "/api/dashboard"),
        ("get", "/api/rules"),
    ],
)
def test_every_data_route_requires_authentication(client, method, path):
    response = getattr(client, method)(path)
    assert response.status_code == 401, f"{path} answered {response.status_code} without auth"


def test_the_openapi_document_lists_the_expected_surface(client):
    paths = client.get("/openapi.json").json()["paths"]
    for expected in (
        "/api/auth/login",
        "/api/assets",
        "/api/scope",
        "/api/scans",
        "/api/findings",
        "/api/changes",
        "/api/graph",
        "/api/attack-paths",
        "/api/reports",
        "/api/audit/verify",
        "/api/dashboard",
    ):
        assert expected in paths, f"{expected} is missing from the API"


# ---------------------------------------------------------------------------
# Scope registry
# ---------------------------------------------------------------------------


def test_creating_a_scope_entry_defaults_to_pending(client, auth_headers):
    """Registering a target is not the same act as authorizing it."""
    response = client.post(
        "/api/scope", json={"domain": "app.acmepay.example"}, headers=auth_headers
    )
    assert response.status_code == 201, response.text
    body = response.json()
    assert body["authorization_status"] == "PENDING"
    assert body["is_authorized_now"] is False
    assert body["authorized_at"] is None


def test_authorizing_a_scope_entry_makes_it_scannable(client, auth_headers):
    entry = client.post(
        "/api/scope",
        json={"domain": "app.acmepay.example", "authorization_status": "AUTHORIZED"},
        headers=auth_headers,
    ).json()
    assert entry["authorization_status"] == "AUTHORIZED"
    assert entry["is_authorized_now"] is True
    assert entry["authorized_at"] is not None


def test_authorizing_then_revoking_clears_the_attestation(client, auth_headers):
    entry = client.post(
        "/api/scope",
        json={"domain": "app.acmepay.example", "authorization_status": "AUTHORIZED"},
        headers=auth_headers,
    ).json()

    revoked = client.patch(
        f"/api/scope/{entry['id']}",
        json={"authorization_status": "REVOKED"},
        headers=auth_headers,
    ).json()
    assert revoked["authorization_status"] == "REVOKED"
    assert revoked["is_authorized_now"] is False
    # A later re-authorization must set the attestation again rather than
    # inherit a stale claim from before the revocation.
    assert revoked["authorized_at"] is None


def test_an_expired_scope_entry_is_not_scannable(client, auth_headers):
    from datetime import timedelta

    past = (utcnow() - timedelta(days=1)).isoformat()
    entry = client.post(
        "/api/scope",
        json={
            "domain": "old.acmepay.example",
            "authorization_status": "AUTHORIZED",
            "expires_at": past,
        },
        headers=auth_headers,
    ).json()
    assert entry["is_authorized_now"] is False


def test_a_scope_entry_rejects_a_url(client, auth_headers):
    response = client.post(
        "/api/scope",
        json={"domain": "https://app.acmepay.example/admin"},
        headers=auth_headers,
    )
    assert response.status_code == 422


def test_a_scope_entry_rejects_an_invalid_cidr(client, auth_headers):
    response = client.post(
        "/api/scope",
        json={"domain": "net.acmepay.example", "cidr": "10.0.0.0/99"},
        headers=auth_headers,
    )
    assert response.status_code == 422


def test_a_duplicate_scope_entry_is_refused(client, auth_headers):
    payload = {"domain": "dup.acmepay.example"}
    assert client.post("/api/scope", json=payload, headers=auth_headers).status_code == 201
    assert client.post("/api/scope", json=payload, headers=auth_headers).status_code == 409


def test_scope_authorization_change_is_audited(client, auth_headers, session):
    from veyl_api.models import AuditLog

    entry = client.post(
        "/api/scope", json={"domain": "audited.acmepay.example"}, headers=auth_headers
    ).json()
    client.patch(
        f"/api/scope/{entry['id']}",
        json={"authorization_status": "AUTHORIZED"},
        headers=auth_headers,
    )
    session.expire_all()
    entries = list(
        session.execute(
            select(AuditLog).where(AuditLog.action == "SCOPE_AUTHORIZATION_CHANGED")
        ).scalars()
    )
    assert len(entries) == 1
    assert "PENDING -> AUTHORIZED" in entries[0].detail


# ---------------------------------------------------------------------------
# Scanning against real authorized scope
# ---------------------------------------------------------------------------


@pytest.fixture()
def scannable(client, auth_headers, demo_server):
    """An authorized scope entry pointing at the bundled AcmePay service.

    ``demo_server`` is a real HTTP server on a real port; the entry opts in to a
    port override so the ephemeral port can be scanned.
    """
    entry = client.post(
        "/api/scope",
        json={
            "domain": "127.0.0.1",
            "authorization_status": "AUTHORIZED",
            "allow_port_override": True,
            "environment": "PRODUCTION",
        },
        headers=auth_headers,
    ).json()
    return {"entry": entry, "port": demo_server}


def test_scanning_with_no_authorized_scope_is_refused_with_a_reason(client, auth_headers):
    response = client.post("/api/scans", json={}, headers=auth_headers)
    assert response.status_code == 400
    detail = response.json()["detail"]
    assert "no authorized" in detail["message"]


def test_scanning_a_pending_entry_is_refused(client, auth_headers):
    entry = client.post(
        "/api/scope", json={"domain": "127.0.0.1"}, headers=auth_headers
    ).json()
    response = client.post(
        "/api/scans", json={"scope_entry_ids": [entry["id"]]}, headers=auth_headers
    )
    assert response.status_code == 400
    assert "no authorized" in response.json()["detail"]["message"]


def test_a_port_override_is_refused_without_explicit_opt_in(client, auth_headers):
    """Honoring it silently would scan ports nobody authorized."""
    client.post(
        "/api/scope",
        json={"domain": "127.0.0.1", "authorization_status": "AUTHORIZED"},
        headers=auth_headers,
    )
    response = client.post(
        "/api/scans", json={"port_override": [8080]}, headers=auth_headers
    )
    assert response.status_code == 400
    assert "allow_port_override" in response.json()["detail"]


def test_a_scan_discovers_assets_and_creates_findings(client, auth_headers, scannable):
    response = client.post(
        "/api/scans",
        json={"label": "integration", "port_override": [scannable["port"]]},
        headers=auth_headers,
    )
    assert response.status_code == 201, response.text
    scan = response.json()
    assert scan["status"] == "COMPLETED"
    assert scan["targets_scanned"] == 1
    assert scan["assets_found"] >= 1
    # The day7 demo profile serves /admin without a challenge and sets wildcard
    # CORS, so findings are expected. Asserting a floor rather than an exact
    # count keeps this robust to rule additions.
    assert scan["findings_created"] >= 1

    findings = client.get("/api/findings", headers=auth_headers).json()
    assert findings["total"] >= 1


def test_findings_carry_evidence_a_detection_explanation_and_an_impact(
    client, auth_headers, scannable
):
    """The product's central claim, asserted end to end through the API."""
    client.post(
        "/api/scans",
        json={"port_override": [scannable["port"]]},
        headers=auth_headers,
    )
    page = client.get("/api/findings", headers=auth_headers).json()
    assert page["total"] >= 1

    for summary in page["items"]:
        detail = client.get(f"/api/findings/{summary['id']}", headers=auth_headers).json()
        assert detail["detection_explanation"], f"{detail['rule_id']} has no detection explanation"
        assert detail["impact"], f"{detail['rule_id']} has no impact statement"
        assert detail["remediation_summary"], f"{detail['rule_id']} has no remediation"
        assert detail["risk_explanation"], f"{detail['rule_id']} has no priority rationale"
        assert detail["evidence"], f"{detail['rule_id']} has no evidence attached"
        for item in detail["evidence"]:
            assert item["provenance"] == "OBSERVED"
            assert item["matcher"]
            assert item["checksum"]
            assert item["detail"] != {} or item["summary"]


def test_a_scan_records_an_audit_trail(client, auth_headers, scannable, session):
    from veyl_api.models import AuditLog

    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    session.expire_all()
    actions = {
        entry.action
        for entry in session.execute(select(AuditLog)).scalars()
    }
    assert "SCAN_STARTED" in actions
    assert "SCAN_COMPLETED" in actions


def test_the_audit_chain_verifies_after_a_scan(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    body = client.get("/api/audit/verify", headers=auth_headers).json()
    assert body["is_valid"] is True
    assert body["entries_checked"] > 0
    assert body["first_bad_entry_id"] is None


# ---------------------------------------------------------------------------
# Assets and business context
# ---------------------------------------------------------------------------


def test_asset_context_can_be_set_and_rescores_findings(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    asset = client.get("/api/assets", headers=auth_headers).json()["items"][0]

    before = client.get(
        f"/api/findings?asset_id={asset['id']}", headers=auth_headers
    ).json()["items"]
    assert before

    context = client.put(
        f"/api/assets/{asset['id']}/context",
        json={
            "business_criticality": "CRITICAL",
            "data_classification": "CONFIDENTIAL",
            "business_function": "PAYMENTS",
            "internet_exposed": True,
        },
        headers=auth_headers,
    )
    assert context.status_code == 200, context.text
    body = context.json()
    assert body["business_criticality"] == "CRITICAL"
    # A value asserted by a person must never keep an INFERRED label.
    assert body["context_source"] == "USER_PROVIDED"

    rescored = client.post(f"/api/assets/{asset['id']}/rescore", headers=auth_headers)
    assert rescored.status_code == 200
    assert rescored.json()["findings_rescored"] >= 1

    after = client.get(
        f"/api/findings?asset_id={asset['id']}", headers=auth_headers
    ).json()["items"]
    # Business context must materially change priority, not just be stored.
    assert max(f["risk_score"] for f in after) >= max(f["risk_score"] for f in before)


def test_internet_exposed_is_only_settable_by_the_organization(client, auth_headers, scannable):
    """A scanner can never assert internet exposure; only a human can."""
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    asset = client.get("/api/assets", headers=auth_headers).json()["items"][0]
    # The scan reached the host, but did not claim it faces the internet.
    assert asset["reachable"] is True
    assert asset["internet_exposed"] is False

    client.put(
        f"/api/assets/{asset['id']}/context",
        json={"internet_exposed": True},
        headers=auth_headers,
    )
    updated = client.get(f"/api/assets/{asset['id']}", headers=auth_headers).json()
    assert updated["internet_exposed"] is True


def test_finding_status_change_records_history(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    finding = client.get("/api/findings", headers=auth_headers).json()["items"][0]

    response = client.patch(
        f"/api/findings/{finding['id']}/status",
        json={"status": "ACKNOWLEDGED", "note": "triage in progress"},
        headers=auth_headers,
    )
    assert response.status_code == 200
    assert response.json()["status"] == "ACKNOWLEDGED"

    history = client.get(
        f"/api/findings/{finding['id']}/history", headers=auth_headers
    ).json()
    assert any(e["event_type"] == "STATUS_CHANGED" for e in history)
    assert any(e["from_value"] == "OPEN" for e in history)


def test_remediation_can_be_assigned_and_verified_state_is_reported(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    finding = client.get("/api/findings", headers=auth_headers).json()["items"][0]

    response = client.put(
        f"/api/findings/{finding['id']}/remediation",
        json={"priority": "URGENT", "notes": "blocked on vendor patch"},
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["priority"] == "URGENT"
    # Not yet verified: nothing rescanned to prove it is gone.
    assert body["verified_at"] is None


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------


def test_an_executive_html_report_embeds_evidence(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    response = client.post(
        "/api/reports",
        json={"kind": "EXECUTIVE", "fmt": "HTML"},
        headers=auth_headers,
    )
    assert response.status_code == 201, response.text
    report = response.json()
    assert report["status"] == "READY"
    assert report["checksum"]
    assert report["download_url"]

    download = client.get(
        f"/api/reports/{report['id']}/download", headers=auth_headers
    )
    assert download.status_code == 200
    body = download.text
    assert "<!DOCTYPE html>" in body
    assert "AcmePay" in body
    # The report must state its own limits rather than implying completeness.
    assert "potential" in body.lower()
    assert "How to read this report" in body


def test_a_technical_json_report_is_machine_readable(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    report = client.post(
        "/api/reports", json={"kind": "TECHNICAL", "fmt": "JSON"}, headers=auth_headers
    ).json()

    payload = client.get(
        f"/api/reports/{report['id']}/download", headers=auth_headers
    ).json()
    assert payload["report"]["kind"] == "TECHNICAL"
    assert payload["summary"]["open_findings"] >= 1
    assert payload["findings"]
    for finding in payload["findings"]:
        assert finding["evidence"], f"{finding['rule_id']} reported without evidence"
        assert finding["detection_explanation"]


def test_pdf_is_refused_explicitly_rather_than_faked(client, auth_headers):
    response = client.post(
        "/api/reports", json={"kind": "EXECUTIVE", "fmt": "PDF"}, headers=auth_headers
    )
    assert response.status_code == 501
    assert "not implemented" in response.json()["detail"]


# ---------------------------------------------------------------------------
# Graph and attack paths
# ---------------------------------------------------------------------------


def test_the_graph_contains_nodes_and_edges_after_a_scan(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    body = client.get("/api/graph", headers=auth_headers).json()
    assert body["node_count"] >= 1
    assert body["nodes"]
    for node in body["nodes"]:
        assert ":" in node["node_key"]  # stable "type:identifier" keys


def test_attack_paths_are_stated_as_potential_with_limitations(client, auth_headers, scannable):
    client.post(
        "/api/scans", json={"port_override": [scannable["port"]]}, headers=auth_headers
    )
    client.post("/api/attack-paths/recompute", headers=auth_headers)

    page = client.get("/api/attack-paths", headers=auth_headers).json()
    for path in page["items"]:
        # Never claim exploitation that was not attempted.
        assert path["state"] == "POTENTIAL"
        assert path["limitations"], f"{path['name']} has no limitations statement"


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------


def test_the_rule_catalogue_is_inspectable(client, auth_headers):
    rules = client.get("/api/rules", headers=auth_headers).json()
    assert len(rules) >= 10
    for rule in rules:
        assert rule["rule_id"].startswith("VEYL-")
        assert rule["description"]
        assert rule["requires_observations"], f"{rule['rule_id']} declares no observation kinds"


def test_an_unknown_rule_id_is_a_404(client, auth_headers):
    assert client.get("/api/rules/VEYL-NOPE-999", headers=auth_headers).status_code == 404


# ---------------------------------------------------------------------------
# Members and RBAC
# ---------------------------------------------------------------------------


def test_an_admin_can_add_a_member(client, auth_headers):
    response = client.post(
        "/api/members",
        json={
            "email": f"analyst-{uuid.uuid4().hex[:6]}@acmepay.example",
            "password": STRONG_PASSWORD,
            "role": "SECURITY_ANALYST",
            "full_name": "Sam Analyst",
        },
        headers=auth_headers,
    )
    assert response.status_code == 201, response.text
    assert response.json()["role"] == "SECURITY_ANALYST"


def test_a_weak_password_is_refused(client, auth_headers):
    response = client.post(
        "/api/members",
        json={
            "email": "weak@acmepay.example",
            "password": "password1234",
            "role": "ENGINEER",
            "full_name": "Weak Password",
        },
        headers=auth_headers,
    )
    assert response.status_code == 422


def test_an_admin_cannot_demote_themselves(client, auth_headers, admin, session):
    """Otherwise an organization can be left with no administrator."""
    membership = session.execute(
        select(OrganizationMember).where(
            OrganizationMember.user_id == admin["user"].id
        )
    ).scalar_one()
    response = client.patch(
        f"/api/members/{membership.id}",
        json={"role": "ENGINEER"},
        headers=auth_headers,
    )
    assert response.status_code == 400
    assert "cannot change your own role" in response.json()["detail"]


def test_an_admin_cannot_deactivate_themselves(client, auth_headers, admin, session):
    membership = session.execute(
        select(OrganizationMember).where(
            OrganizationMember.user_id == admin["user"].id
        )
    ).scalar_one()
    response = client.patch(
        f"/api/members/{membership.id}", json={"is_active": False}, headers=auth_headers
    )
    assert response.status_code == 400


def test_a_non_admin_cannot_add_members(client, session, admin, auth_headers):
    """An ENGINEER must be refused by capability, not by UI convention."""
    email = f"engineer-{uuid.uuid4().hex[:6]}@acmepay.example"
    created = client.post(
        "/api/members",
        json={"email": email, "password": STRONG_PASSWORD, "role": "ENGINEER", "full_name": "Test Person"},
        headers=auth_headers,
    )
    assert created.status_code == 201

    login = client.post(
        "/api/auth/login", json={"email": email, "password": STRONG_PASSWORD}
    ).json()
    engineer_headers = {"Authorization": f"Bearer {login['access_token']}"}

    # Read is allowed; write is not.
    assert client.get("/api/assets", headers=engineer_headers).status_code == 200
    assert client.get("/api/audit", headers=engineer_headers).status_code == 403
    assert (
        client.post(
            "/api/members",
            json={"email": "x@y.example", "password": STRONG_PASSWORD, "full_name": "X Y"},
            headers=engineer_headers,
        ).status_code
        == 403
    )


def test_an_executive_can_read_reports_but_not_scan(client, auth_headers, session):
    email = f"exec-{uuid.uuid4().hex[:6]}@acmepay.example"
    client.post(
        "/api/members",
        json={"email": email, "password": STRONG_PASSWORD, "role": "EXECUTIVE", "full_name": "Test Person"},
        headers=auth_headers,
    )
    login = client.post(
        "/api/auth/login", json={"email": email, "password": STRONG_PASSWORD}
    ).json()
    headers = {"Authorization": f"Bearer {login['access_token']}"}

    assert client.get("/api/findings", headers=headers).status_code == 200
    assert client.get("/api/reports", headers=headers).status_code == 200
    assert client.post("/api/scans", json={}, headers=headers).status_code == 403
    assert client.get("/api/audit", headers=headers).status_code == 403


def test_removing_a_member_revokes_their_access_immediately(client, auth_headers, session):
    email = f"temp-{uuid.uuid4().hex[:6]}@acmepay.example"
    member = client.post(
        "/api/members",
        json={"email": email, "password": STRONG_PASSWORD, "role": "SECURITY_ANALYST", "full_name": "Test Person"},
        headers=auth_headers,
    ).json()

    login = client.post(
        "/api/auth/login", json={"email": email, "password": STRONG_PASSWORD}
    ).json()
    headers = {"Authorization": f"Bearer {login['access_token']}"}
    assert client.get("/api/findings", headers=headers).status_code == 200

    assert client.delete(f"/api/members/{member['id']}", headers=auth_headers).status_code == 204

    # The token is still cryptographically valid; authorization is re-read.
    assert client.get("/api/findings", headers=headers).status_code == 403


# ---------------------------------------------------------------------------
# Tenant isolation
# ---------------------------------------------------------------------------


@pytest.fixture()
def two_tenants(client, session, admin, auth_headers, demo_server):
    """A second organization with its own admin, scope, and findings.

    The second administrator also carries a TOTP factor, because §27 refuses an
    administrative account without one. Its secret is fixed so tests can sign in
    as either tenant.
    """
    from veyl_api.api.routes.auth import _hash_totp_secret

    other_secret = "MFRGGZDFMZTWQ2LKMFRGGZDFMZTWQ2LK"
    other_org = Organization(
        name="Contoso", slug=f"contoso-{uuid.uuid4().hex[:8]}", primary_domain="contoso.example"
    )
    session.add(other_org)
    session.flush()

    other_user = User(
        email=f"admin-{uuid.uuid4().hex[:6]}@contoso.example",
        full_name="Chandra Contoso",
        password_hash=hash_password(STRONG_PASSWORD),
        is_active=True,
        mfa_enabled=True,
        mfa_secret_hash=_hash_totp_secret(other_secret),
        mfa_enrolled_at=utcnow(),
    )
    session.add(other_user)
    session.flush()
    session.add(
        OrganizationMember(
            organization_id=other_org.id,
            user_id=other_user.id,
            role=OrganizationRole.ADMIN,
            is_active=True,
        )
    )
    session.commit()

    other_login = client.post(
        "/api/auth/login",
        json={
            "email": other_user.email,
            "password": STRONG_PASSWORD,
            "totp_code": totp_for(other_secret),
        },
    )
    assert other_login.status_code == 200, other_login.text
    other_headers = {"Authorization": f"Bearer {other_login.json()['access_token']}"}

    # AcmePay (the primary tenant) scans and gets real findings.
    client.post(
        "/api/scope",
        json={
            "domain": "127.0.0.1",
            "authorization_status": "AUTHORIZED",
            "allow_port_override": True,
        },
        headers=auth_headers,
    )
    client.post(
        "/api/scans", json={"port_override": [demo_server]}, headers=auth_headers
    )

    return {
        "other_org": other_org,
        "other_user": other_user,
        "other_secret": other_secret,
        "other_headers": other_headers,
    }


def test_findings_do_not_leak_between_organizations(client, auth_headers, two_tenants):
    mine = client.get("/api/findings", headers=auth_headers).json()
    theirs = client.get("/api/findings", headers=two_tenants["other_headers"]).json()

    assert mine["total"] >= 1
    assert theirs["total"] == 0, "the second tenant saw the first tenant's findings"


def test_assets_do_not_leak_between_organizations(client, auth_headers, two_tenants):
    assert client.get("/api/assets", headers=auth_headers).json()["total"] >= 1
    assert client.get("/api/assets", headers=two_tenants["other_headers"]).json()["total"] == 0


def test_scope_does_not_leak_between_organizations(client, auth_headers, two_tenants):
    assert client.get("/api/scope", headers=auth_headers).json()["total"] >= 1
    assert client.get("/api/scope", headers=two_tenants["other_headers"]).json()["total"] == 0


def test_fetching_another_tenants_finding_is_a_404_not_a_403(client, auth_headers, two_tenants):
    """403 would confirm the identifier exists, which is an enumeration oracle."""
    finding = client.get("/api/findings", headers=auth_headers).json()["items"][0]
    response = client.get(
        f"/api/findings/{finding['id']}", headers=two_tenants["other_headers"]
    )
    assert response.status_code == 404


def test_fetching_another_tenants_asset_is_a_404(client, auth_headers, two_tenants):
    asset = client.get("/api/assets", headers=auth_headers).json()["items"][0]
    response = client.get(
        f"/api/assets/{asset['id']}", headers=two_tenants["other_headers"]
    )
    assert response.status_code == 404


def test_another_tenants_scan_id_cannot_be_used_to_scan(client, auth_headers, two_tenants):
    entry = client.get("/api/scope", headers=auth_headers).json()["items"][0]
    response = client.post(
        "/api/scans",
        json={"scope_entry_ids": [entry["id"]]},
        headers=two_tenants["other_headers"],
    )
    assert response.status_code == 404


def test_the_audit_chain_is_per_tenant(client, auth_headers, two_tenants):
    """One tenant's entries must not appear in, or break, another's chain."""
    mine = client.get("/api/audit", headers=auth_headers).json()
    theirs = client.get("/api/audit", headers=two_tenants["other_headers"]).json()

    assert mine["total"] >= 1
    # Contoso only logged in, so it has entries too — but none of AcmePay's.
    assert theirs["total"] >= 1
    my_ids = {e["id"] for e in mine["items"]}
    assert not (my_ids & {e["id"] for e in theirs["items"]})

    assert client.get("/api/audit/verify", headers=auth_headers).json()["is_valid"] is True
    assert (
        client.get("/api/audit/verify", headers=two_tenants["other_headers"]).json()["is_valid"]
        is True
    )


def test_dashboard_numbers_are_scoped_to_the_tenant(client, auth_headers, two_tenants):
    mine = client.get("/api/dashboard", headers=auth_headers).json()
    theirs = client.get("/api/dashboard", headers=two_tenants["other_headers"]).json()

    assert mine["asset_count"] >= 1
    assert mine["open_finding_count"] >= 1
    assert theirs["asset_count"] == 0
    assert theirs["open_finding_count"] == 0
    assert theirs["scope_entry_count"] == 0


def test_two_organizations_require_explicit_selection(client, session, auth_headers, two_tenants):
    """A user in two organizations must name one; guessing is unsafe."""
    admin_email = client.get("/api/auth/me", headers=auth_headers).json()["email"]
    user = session.execute(select(User).where(User.email == admin_email)).scalar_one()

    session.add(
        OrganizationMember(
            organization_id=two_tenants["other_org"].id,
            user_id=user.id,
            role=OrganizationRole.EXECUTIVE,
            is_active=True,
        )
    )
    session.commit()

    # A fresh token now carries no organization-specific choice usable on its own.
    login = login_as(client, admin_email, ADMIN_TOTP_SECRET)
    # Login resolves to the single organization the payload named (None), so it
    # must now refuse rather than pick one arbitrarily.
    assert login.status_code == 400
    assert "multiple organizations" in login.json()["detail"]

    # Naming one works, and the role is taken from that membership.
    named = client.post(
        "/api/auth/login",
        json={
            "email": admin_email,
            "password": STRONG_PASSWORD,
            "totp_code": totp_for(ADMIN_TOTP_SECRET),
            "organization_slug": two_tenants["other_org"].slug,
        },
    )
    assert named.status_code == 200
    headers = {"Authorization": f"Bearer {named.json()['access_token']}"}
    assert client.get("/api/auth/me", headers=headers).json()["role"] == "EXECUTIVE"


# ---------------------------------------------------------------------------
# The privileged-role policy, at the point a role is granted
# ---------------------------------------------------------------------------


def test_an_admin_role_cannot_be_granted_to_an_account_without_a_factor(client, auth_headers):
    """Granting first and enrolling later would leave a window with no factor."""
    response = client.post(
        "/api/members",
        headers=auth_headers,
        json={
            "email": f"newadmin-{uuid.uuid4().hex[:6]}@acmepay.example",
            "password": STRONG_PASSWORD,
            "full_name": "New Admin",
            "role": "ADMIN",
        },
    )
    assert response.status_code == 409
    assert "second factor" in response.json()["detail"]


def test_a_non_privileged_role_is_granted_normally(client, auth_headers):
    """The policy must not become a blanket refusal to add members."""
    response = client.post(
        "/api/members",
        headers=auth_headers,
        json={
            "email": f"analyst-{uuid.uuid4().hex[:6]}@acmepay.example",
            "password": STRONG_PASSWORD,
            "full_name": "Ana Analyst",
            "role": "SECURITY_ANALYST",
        },
    )
    assert response.status_code == 201
    assert response.json()["role"] == "SECURITY_ANALYST"


def test_a_member_without_a_factor_cannot_be_promoted_to_admin(client, auth_headers):
    email = f"promote-{uuid.uuid4().hex[:6]}@acmepay.example"
    created = client.post(
        "/api/members",
        headers=auth_headers,
        json={
            "email": email,
            "password": STRONG_PASSWORD,
            "full_name": "Promote Me",
            "role": "ENGINEER",
        },
    ).json()

    response = client.patch(
        f"/api/members/{created['id']}", headers=auth_headers, json={"role": "ADMIN"}
    )
    assert response.status_code == 409
    assert "second factor" in response.json()["detail"]

    # The membership is unchanged, not partially applied.
    body = client.get(f"/api/members/{created['id']}", headers=auth_headers).json()
    assert body["role"] == "ENGINEER"


def test_a_member_with_a_factor_can_be_promoted_to_admin(client, auth_headers, session):
    """The policy is a requirement, not a prohibition."""
    from veyl_api.api.routes.auth import _hash_totp_secret
    from veyl_api.security.mfa import generate_totp_secret, hash_recovery_codes

    email = f"promotable-{uuid.uuid4().hex[:6]}@acmepay.example"
    created = client.post(
        "/api/members",
        headers=auth_headers,
        json={
            "email": email,
            "password": STRONG_PASSWORD,
            "full_name": "Promotable",
            "role": "ENGINEER",
        },
    ).json()

    session.expire_all()
    user = session.execute(select(User).where(User.email == email)).scalar_one()
    user.mfa_enabled = True
    user.mfa_secret_hash = _hash_totp_secret(generate_totp_secret())
    user.mfa_recovery_hash = hash_recovery_codes(["AAAA-BBBB"])
    session.commit()

    response = client.patch(
        f"/api/members/{created['id']}", headers=auth_headers, json={"role": "ADMIN"}
    )
    assert response.status_code == 200, response.text
    assert response.json()["role"] == "ADMIN"


# ---------------------------------------------------------------------------
# Validation and error handling
# ---------------------------------------------------------------------------


def test_validation_errors_do_not_echo_the_submitted_password(client, auth_headers):
    """A default FastAPI error body includes the input; this one must not.

    Asserted against a distinctive value rather than a short word, because a
    substring check on something like "short" would match the error *type*
    (``string_too_short``) and prove nothing.
    """
    secret = "Zq7-Sup3rSecret-Passphrase-Value"
    response = client.post(
        "/api/members",
        json={"email": "x@y.example", "password": secret, "role": "ENGINEER", "full_name": "A"},
        headers=auth_headers,
    )
    # The payload's password is long enough to pass, so this exercises the
    # success path; the important check is that no response ever contains it.
    assert secret not in response.text

    too_short = "Zq7-Short"
    rejected = client.post(
        "/api/members",
        json={"email": "x@y.example", "password": too_short, "role": "ENGINEER", "full_name": "A"},
        headers=auth_headers,
    )
    assert rejected.status_code == 422
    assert too_short not in rejected.text
    # The error names the rule, not the value.
    assert "string_too_short" in rejected.text or "too_short" in rejected.text


def test_a_malformed_json_body_is_a_422(client, auth_headers):
    response = client.post(
        "/api/scope",
        content=b"{not json",
        headers={**auth_headers, "Content-Type": "application/json"},
    )
    assert response.status_code == 422


def test_an_out_of_range_port_override_is_refused(client, auth_headers):
    entry = client.post(
        "/api/scope",
        json={"domain": "127.0.0.1", "authorization_status": "AUTHORIZED", "allow_port_override": True},
        headers=auth_headers,
    ).json()
    assert entry
    response = client.post(
        "/api/scans", json={"port_override": [70000]}, headers=auth_headers
    )
    assert response.status_code == 422


def test_pagination_bounds_are_enforced(client, auth_headers):
    assert client.get("/api/findings?limit=100000", headers=auth_headers).status_code == 422
    assert client.get("/api/findings?limit=0", headers=auth_headers).status_code == 422


def test_unknown_route_is_a_404(client, auth_headers):
    assert client.get("/api/does-not-exist", headers=auth_headers).status_code == 404


def test_member_id_helper_is_only_used_by_tests():
    """Guard against the test helper leaking into a route."""
    generated = members_route.new_member_id()
    assert isinstance(generated, str) and len(generated) == 36
